"""Add image_file column to user

Revision ID: 369578793225
Revises: 1e9464bad39d
Create Date: 2024-01-07 00:26:31.657488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369578793225'
down_revision = '1e9464bad39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
